const prod = {
  url: {
    url: "https://convie.herokuapp.com/",
    url_login: "https://convie.herokuapp.com/login",
    url_register: "https://convie.herokuapp.com/register",
    url_logout: "https://convie.herokuapp.com/logout",
    url_customerAddress: "https://convie.herokuapp.com/customerAddress",
    url_picture: "https://convie.herokuapp.com/picture",
    url_uploads: "https://convie.herokuapp.com/uploads",
    url_account: "https://convie.herokuapp.com/account",
    url_products: "https://convie.herokuapp.com/products",
    url_userInfo: "https://convie.herokuapp.com/userInfo",
    url_order: "https://convie.herokuapp.com/order",
    url_history: "https://convie.herokuapp.com/history",
    url_orders: "https://convie.herokuapp.com/orders",
    url_onlyAdmin: "https://convie.herokuapp.com/onlyAdmin",
    url_pName: "https://convie.herokuapp.com/pName",
    url_uName: "https://convie.herokuapp.com/uName",
    url_users: "https://convie.herokuapp.com/users",
    url_product: "https://convie.herokuapp.com/product",
    url_addProduct: "https://convie.herokuapp.com/addProduct",
    url_addAdmin: "https://convie.herokuapp.com/addAdmin",
    url_sessionInfo: "https://convie.herokuapp.com/sessionInfo",
  },
};
const dev = {
  url: {
    url: "http://localhost:5000",
    url_login: "http://localhost:5000/login",
    url_register: "http://localhost:5000/register",
    url_logout: "http://localhost:5000/logout",
    url_customerAddress: "http://localhost:5000/customerAddress",
    url_picture: "http://localhost:5000/picture",
    url_uploads: "http://localhost:5000/uploads",
    url_account: "http://localhost:5000/account",
    url_products: "http://localhost:5000/products",
    url_userInfo: "http://localhost:5000/userInfo",
    url_order: "http://localhost:5000/order",
    url_history: "http://localhost:5000/history",
    url_orders: "http://localhost:5000/orders",
    url_onlyAdmin: "http://localhost:5000/onlyAdmin",
    url_pName: "http://localhost:5000/pName",
    url_uName: "http://localhost:5000/uName",
    url_users: "http://localhost:5000/users",
    url_product: "http://localhost:5000/product",
    url_addProduct: "http://localhost:5000/addProduct",
    url_addAdmin: "http://localhost:5000/addAdmin",
    url_sessionInfo: "http://localhost:5000/sessionInfo",
  },
};

export const config = process.env.NODE_ENV === `development` ? dev : prod;
